# Generated by Django 6.0 on 2026-01-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='yamlFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaml', models.FileField(upload_to='')),
                ('slot_name', models.CharField(max_length=32)),
                ('last_modified', models.DateTimeField()),
            ],
        ),
    ]
