# Generated by Django 6.0 on 2026-01-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='yamlFile',
        ),
    ]
