# Generated by Django 6.0 on 2026-04-06 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0003_lobby_name'),
        ('user_yamls', '0003_remove_user_yamls_yaml_file_user_yamls_game_options'),
        ('users', '0002_users_delete_yamlfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='UserAccount',
        ),
    ]
