# Generated by Django 6.0 on 2026-04-14 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0004_alter_lobby_host_id'),
        ('user_yamls', '0004_alter_user_yamls_user_id'),
        ('users', '0003_rename_users_useraccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
