# Generated by Django 6.0 on 2026-01-08 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_users_delete_yamlfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_yamls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaml_file', models.FileField(upload_to='')),
                ('last_edited', models.DateField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
