# Generated by Django 6.0 on 2026-01-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_yamls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_yamls',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='user_yamls',
            name='game_name',
            field=models.CharField(default='Default Game Name', max_length=50),
        ),
        migrations.AddField(
            model_name='user_yamls',
            name='slot',
            field=models.CharField(default='Default Slot', max_length=16),
        ),
    ]
