# Generated by Django 6.0 on 2026-01-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_yamls', '0002_user_yamls_description_user_yamls_game_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_yamls',
            name='yaml_file',
        ),
        migrations.AddField(
            model_name='user_yamls',
            name='game_options',
            field=models.CharField(default='EMPTY SETTINGS'),
        ),
    ]
