# Generated by Django 6.0 on 2026-05-25 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_yamls', '0004_alter_user_yamls_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_yamls',
            old_name='slot',
            new_name='slot_name',
        ),
    ]
