# Generated by Django 6.0 on 2026-05-26 00:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0006_rename_player_yaml_slot_slot_id'),
        ('user_yamls', '0005_rename_slot_user_yamls_slot_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_yamls',
            new_name='Yaml',
        ),
    ]
