# Generated by Django 6.0 on 2026-02-06 22:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_yamls', '0003_remove_user_yamls_yaml_file_user_yamls_game_options'),
        ('users', '0002_users_delete_yamlfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date(2026, 2, 6))),
                ('is_async', models.BooleanField(default=False)),
                ('description', models.CharField(default='')),
                ('host_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
        migrations.CreateModel(
            name='LobbyConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lobby_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lobby.lobby')),
                ('player_yaml', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_yamls.user_yamls')),
            ],
        ),
    ]
