# Generated by Django 6.0 on 2026-02-06 22:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
