# Generated by Django 6.0 on 2026-02-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0002_alter_lobby_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='name',
            field=models.CharField(default='Lobby'),
        ),
    ]
