# Generated by Django 6.0 on 2026-05-26 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0004_alter_lobby_host_id'),
        ('user_yamls', '0005_rename_slot_user_yamls_slot_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LobbyConnection',
            new_name='Slot',
        ),
    ]
