# Generated by Django 6.0 on 2026-05-26 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0005_rename_lobbyconnection_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='player_yaml',
            new_name='slot_id',
        ),
    ]
